# Copyright (c) 2019 Payara Foundation and/or its affiliates.
# All rights reserved.
#
# The contents of this file are subject to the terms of the Common Development
# and Distribution License("CDDL") (collectively, the "License").  You
# may not use this file except in compliance with the License.  You can
# obtain a copy of the License at
# https://glassfish.dev.java.net/public/CDDL+GPL_1_1.html
# or packager/legal/LICENSE.txt.  See the License for the specific
# language governing permissions and limitations under the License.
#
# When distributing the software, include this License Header Notice in each
# file and include the License file at packager/legal/LICENSE.txt.

# This file controls continuous integration builds on GitLab CI.

main:
    image: ubuntu:latest
        # `maven:slim` and `maven:3-jdk-8` cause test failure due to `java.lang.Exception: Method testConstructorsLocation should have no parameters`, see https://github.com/payara/Payara/issues/2895 for details
    script:
        - apt-get update && apt-get install --yes openjdk-8-jdk
        - apt-get install --yes maven
            # separate installation of `maven` necessary in order to avoid installation of unsupported OpenJDK 11 JRE, see https://askubuntu.com/questions/1058271/why-is-openjdk-11-jre-installed-together-with-maven-when-openjdk-8-jdk-is-specif an explanation
        - mvn --batch-mode install &> /tmp/build.log || (tail -n 1000 /tmp/build.log; exit 1)
        - tail -n 1000 /tmp/build.log
            # this duplication is necessary in order to be able to display the tail of `build.log` both after failure and success because `||` has be used rather than `;` in order to avoid the script being terminated immediately after a failure in the build command
